// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaibazsgmqoosenurkut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaWJhenNnbXFvb3NlbnVya3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzA5NzcsImV4cCI6MjA1ODQwNjk3N30.6L5tYckTiM4-I4sNzuJGyRkdHA-Ovd5MnN8DmOooKzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);